I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/code/day3/pool.rpy", line 217, in script
    pause 10.0
  File "renpy/common/000statements.rpy", line 414, in execute_pause
    renpy.with_statement(Pause(delay))
IOError: Couldn't find file 'sounds/sound/xxx.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/code/day3/pool.rpy", line 217, in script
    pause 10.0
  File "/Users/Pedobear/Projects/RenPy/renpy/ast.py", line 1861, in execute
    self.call("execute")
  File "/Users/Pedobear/Projects/RenPy/renpy/ast.py", line 1849, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Users/Pedobear/Projects/RenPy/renpy/statements.py", line 203, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 414, in execute_pause
    renpy.with_statement(Pause(delay))
  File "/Users/Pedobear/Projects/RenPy/renpy/exports.py", line 1481, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Users/Pedobear/Projects/RenPy/renpy/display/core.py", line 2227, in do_with
    clear=clear)
  File "/Users/Pedobear/Projects/RenPy/renpy/display/core.py", line 2672, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/Users/Pedobear/Projects/RenPy/renpy/display/core.py", line 3344, in interact_core
    renpy.audio.audio.periodic()
  File "/Users/Pedobear/Projects/RenPy/renpy/audio/audio.py", line 993, in periodic_thread_main
    periodic_pass()
  File "/Users/Pedobear/Projects/RenPy/renpy/audio/audio.py", line 937, in periodic_pass
    c.periodic()
  File "/Users/Pedobear/Projects/RenPy/renpy/audio/audio.py", line 419, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "/Users/Pedobear/Projects/RenPy/renpy/audio/audio.py", line 71, in load
    rv = renpy.loader.load(fn)
  File "/Users/Pedobear/Projects/RenPy/renpy/loader.py", line 576, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'sounds/sound/xxx.mp3'.

Darwin-18.2.0-x86_64-i386-64bit
Ren'Py 7.1.3.1092
Bled_Moon ver. 1.1 Beta
Wed Dec 26 16:30:16 2018
